version: "3"
networks:
   hyperledger-ov:
      external:     
         name: hyperledger-ov 
services:
   cli:
      hostname: cli
      image: hyperledger/fabric-tools:1.3.0
      environment:
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
         - GOPATH=/opt/gopath
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_LOGGING_LEVEL=DEBUG
         - CORE_PEER_ID=cli
         - CORE_PEER_ADDRESS=peer0.agetic.gob.bo:7051
         - CORE_PEER_LOCALMSPID=AgeticMSP
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/agetic.gob.bo/peers/peer0.agetic.gob.bo/tls/server.crt
         - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/agetic.gob.bo/peers/peer0.agetic.gob.bo/tls/server.key
         - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/agetic.gob.bo/peers/peer0.agetic.gob.bo/tls/ca.crt
         - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/agetic.gob.bo/users/Admin@agetic.gob.bo/msp
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      volumes:
         - /var/run/:/host/var/run/
         - ./chaincode/:/opt/gopath/src/github.com/chaincode
         - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config
         - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  
      command: sleep 3600
      deploy:
         replicas: 1
         restart_policy:
            condition: on-failure
         placement:
            constraints:
               - node.hostname == Aquí viene el nombre del host     
      networks:
         hyperledger-ov:
            aliases:
               - cli

